version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../mysql-confd:/etc/mysql/conf.d  
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -e production -C config/puma.rb"
    volumes:
      - .:/myapp 
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - "8080:8080"
    links:
      - db

  web-nginx:
    build:
      context: containers/nginx
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/myapp.conf
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  public-data:
  tmp-data: